@echo off
REM MemoGraph MCP Server Wrapper
REM Auto-generated by setup_mcp.py

cd /d "c:\Users\INDIRAKUMARS\Documents\Projects\MemoGraph"

REM Use the Python that has memograph installed
"C:\python 3.11.9\python.exe" -m memograph.mcp.run_server
