/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MemoGraphPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  memoGraphUrl: "http://localhost:5000",
  apiKey: "",
  autoSync: false,
  syncInterval: 300,
  debounceDelay: 300,
  conflictStrategy: "newest_wins",
  excludedFolders: [".obsidian", ".trash"],
  includedTags: []
};
var MemoGraphSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "MemoGraph Sync Settings" });
    new import_obsidian.Setting(containerEl).setName("MemoGraph URL").setDesc("URL of your MemoGraph server").addText((text) => text.setPlaceholder("http://localhost:5000").setValue(this.plugin.settings.memoGraphUrl).onChange(async (value) => {
      this.plugin.settings.memoGraphUrl = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("API Key").setDesc("API key for authentication (optional)").addText((text) => text.setPlaceholder("Enter your API key").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
      this.plugin.settings.apiKey = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Auto Sync").setDesc("Automatically sync changes").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoSync).onChange(async (value) => {
      this.plugin.settings.autoSync = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Sync Interval").setDesc("Seconds between automatic syncs (if enabled)").addText((text) => text.setPlaceholder("300").setValue(String(this.plugin.settings.syncInterval)).onChange(async (value) => {
      const num = Number(value);
      if (!isNaN(num) && num > 0) {
        this.plugin.settings.syncInterval = num;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("Debounce Delay").setDesc("Milliseconds to wait after file changes before syncing (prevents sync storms)").addText((text) => text.setPlaceholder("300").setValue(String(this.plugin.settings.debounceDelay)).onChange(async (value) => {
      const num = Number(value);
      if (!isNaN(num) && num >= 0) {
        this.plugin.settings.debounceDelay = num;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("Conflict Strategy").setDesc("How to resolve sync conflicts").addDropdown((dropdown) => dropdown.addOption("obsidian_wins", "Obsidian Wins").addOption("memograph_wins", "MemoGraph Wins").addOption("newest_wins", "Newest Wins").addOption("manual", "Manual Resolution").setValue(this.plugin.settings.conflictStrategy).onChange(async (value) => {
      this.plugin.settings.conflictStrategy = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Excluded Folders").setDesc("Folders to exclude from sync (comma-separated)").addText((text) => text.setPlaceholder(".obsidian, .trash").setValue(this.plugin.settings.excludedFolders.join(", ")).onChange(async (value) => {
      this.plugin.settings.excludedFolders = value.split(",").map((f) => f.trim()).filter((f) => f.length > 0);
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Included Tags").setDesc("Only sync notes with these tags (comma-separated, empty = sync all)").addText((text) => text.setPlaceholder("memograph, sync").setValue(this.plugin.settings.includedTags.join(", ")).onChange(async (value) => {
      this.plugin.settings.includedTags = value.split(",").map((t) => t.trim()).filter((t) => t.length > 0);
      await this.plugin.saveSettings();
    }));
  }
};

// src/sync.ts
var import_obsidian3 = require("obsidian");

// src/conflictModal.ts
var import_obsidian2 = require("obsidian");
var ConflictModal = class extends import_obsidian2.Modal {
  constructor(app, conflictData, onResolve) {
    super(app);
    this.diffViewEl = null;
    this.conflictData = conflictData;
    this.onResolve = onResolve;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("memograph-conflict-modal");
    contentEl.createEl("h2", { text: "Sync Conflict Detected" });
    contentEl.createEl("p", {
      text: `The file "${this.conflictData.filePath}" has conflicting changes.`,
      cls: "conflict-description"
    });
    const timeInfo = contentEl.createDiv({ cls: "conflict-time-info" });
    timeInfo.createEl("div", {
      text: `Local version: ${new Date(this.conflictData.localModified).toLocaleString()}`
    });
    timeInfo.createEl("div", {
      text: `Remote version: ${new Date(this.conflictData.remoteModified).toLocaleString()}`
    });
    this.diffViewEl = contentEl.createDiv({ cls: "conflict-diff-container" });
    this.renderDiffView();
    const buttonContainer = contentEl.createDiv({ cls: "conflict-button-container" });
    const keepLocalBtn = buttonContainer.createEl("button", {
      text: "Keep Local Version",
      cls: "mod-cta"
    });
    keepLocalBtn.addEventListener("click", () => {
      this.onResolve("keep-local");
      this.close();
    });
    const keepRemoteBtn = buttonContainer.createEl("button", {
      text: "Keep Remote Version",
      cls: "mod-cta"
    });
    keepRemoteBtn.addEventListener("click", () => {
      this.onResolve("keep-remote");
      this.close();
    });
    const keepBothBtn = buttonContainer.createEl("button", {
      text: "Keep Both (Merge)",
      cls: "mod-warning"
    });
    keepBothBtn.addEventListener("click", () => {
      const mergedContent = this.createMergedVersion();
      this.onResolve("keep-both", mergedContent);
      this.close();
    });
    const manualBtn = buttonContainer.createEl("button", {
      text: "Edit Manually"
    });
    manualBtn.addEventListener("click", () => {
      this.onResolve("manual");
      this.close();
    });
    const cancelBtn = buttonContainer.createEl("button", {
      text: "Cancel"
    });
    cancelBtn.addEventListener("click", () => {
      this.close();
    });
    this.addStyles();
  }
  renderDiffView() {
    if (!this.diffViewEl)
      return;
    this.diffViewEl.empty();
    const comparisonContainer = this.diffViewEl.createDiv({ cls: "conflict-comparison" });
    const localPanel = comparisonContainer.createDiv({ cls: "conflict-panel conflict-local" });
    localPanel.createEl("h3", { text: "Local Version" });
    const localContent = localPanel.createEl("pre", { cls: "conflict-content" });
    localContent.createEl("code", { text: this.conflictData.localVersion });
    const remotePanel = comparisonContainer.createDiv({ cls: "conflict-panel conflict-remote" });
    remotePanel.createEl("h3", { text: "Remote Version (MemoGraph)" });
    const remoteContent = remotePanel.createEl("pre", { cls: "conflict-content" });
    remoteContent.createEl("code", { text: this.conflictData.remoteVersion });
    this.highlightDifferences(localContent, remoteContent);
  }
  highlightDifferences(localEl, remoteEl) {
    var _a;
    const localLines = this.conflictData.localVersion.split("\n");
    const remoteLines = this.conflictData.remoteVersion.split("\n");
    const maxLines = Math.max(localLines.length, remoteLines.length);
    let diffCount = 0;
    for (let i = 0; i < maxLines; i++) {
      const localLine = localLines[i] || "";
      const remoteLine = remoteLines[i] || "";
      if (localLine !== remoteLine) {
        diffCount++;
      }
    }
    const summary = (_a = this.diffViewEl) == null ? void 0 : _a.createDiv({ cls: "conflict-diff-summary" });
    if (summary) {
      summary.createEl("p", {
        text: `Found ${diffCount} differing lines between versions.`
      });
    }
  }
  createMergedVersion() {
    const merged = `<<<<<<< Local Version (${new Date(this.conflictData.localModified).toLocaleString()})
${this.conflictData.localVersion}
=======
${this.conflictData.remoteVersion}
>>>>>>> Remote Version (MemoGraph) (${new Date(this.conflictData.remoteModified).toLocaleString()})
`;
    return merged;
  }
  addStyles() {
    const styleEl = document.createElement("style");
    styleEl.textContent = `
            .memograph-conflict-modal {
                padding: 20px;
            }

            .conflict-description {
                margin: 10px 0 20px 0;
                color: var(--text-muted);
            }

            .conflict-time-info {
                margin-bottom: 20px;
                padding: 10px;
                background: var(--background-secondary);
                border-radius: 5px;
            }

            .conflict-time-info div {
                margin: 5px 0;
                font-size: 0.9em;
            }

            .conflict-diff-container {
                margin: 20px 0;
                max-height: 400px;
                overflow-y: auto;
                border: 1px solid var(--background-modifier-border);
                border-radius: 5px;
            }

            .conflict-comparison {
                display: flex;
                gap: 10px;
            }

            .conflict-panel {
                flex: 1;
                padding: 10px;
            }

            .conflict-panel h3 {
                margin: 0 0 10px 0;
                font-size: 1em;
                font-weight: 600;
            }

            .conflict-local {
                background: var(--background-secondary);
                border-right: 2px solid var(--interactive-accent);
            }

            .conflict-remote {
                background: var(--background-secondary-alt);
            }

            .conflict-content {
                margin: 0;
                padding: 10px;
                background: var(--background-primary);
                border-radius: 3px;
                font-family: var(--font-monospace);
                font-size: 0.85em;
                white-space: pre-wrap;
                word-wrap: break-word;
                max-height: 300px;
                overflow-y: auto;
            }

            .conflict-diff-summary {
                padding: 10px;
                background: var(--background-secondary);
                border-top: 1px solid var(--background-modifier-border);
                text-align: center;
            }

            .conflict-button-container {
                display: flex;
                gap: 10px;
                justify-content: center;
                margin-top: 20px;
                flex-wrap: wrap;
            }

            .conflict-button-container button {
                padding: 8px 16px;
                cursor: pointer;
            }
        `;
    document.head.appendChild(styleEl);
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/diffView.ts
var DiffView = class {
  /**
   * Compute diff between two text versions
   */
  static computeDiff(localText, remoteText) {
    const localLines = localText.split("\n");
    const remoteLines = remoteText.split("\n");
    const diffResult = {
      localLines: [],
      remoteLines: [],
      stats: {
        added: 0,
        removed: 0,
        modified: 0,
        unchanged: 0
      }
    };
    const maxLines = Math.max(localLines.length, remoteLines.length);
    for (let i = 0; i < maxLines; i++) {
      const localLine = i < localLines.length ? localLines[i] : null;
      const remoteLine = i < remoteLines.length ? remoteLines[i] : null;
      if (localLine === null) {
        diffResult.remoteLines.push({
          type: "added",
          content: remoteLine || "",
          lineNumber: i + 1
        });
        diffResult.stats.added++;
      } else if (remoteLine === null) {
        diffResult.localLines.push({
          type: "removed",
          content: localLine,
          lineNumber: i + 1
        });
        diffResult.stats.removed++;
      } else if (localLine === remoteLine) {
        diffResult.localLines.push({
          type: "unchanged",
          content: localLine,
          lineNumber: i + 1,
          pairLineNumber: i + 1
        });
        diffResult.remoteLines.push({
          type: "unchanged",
          content: remoteLine,
          lineNumber: i + 1,
          pairLineNumber: i + 1
        });
        diffResult.stats.unchanged++;
      } else {
        diffResult.localLines.push({
          type: "modified",
          content: localLine,
          lineNumber: i + 1,
          pairLineNumber: i + 1
        });
        diffResult.remoteLines.push({
          type: "modified",
          content: remoteLine,
          lineNumber: i + 1,
          pairLineNumber: i + 1
        });
        diffResult.stats.modified++;
      }
    }
    return diffResult;
  }
  /**
   * Render unified diff view
   */
  static renderUnifiedDiff(container, localText, remoteText) {
    const diff = this.computeDiff(localText, remoteText);
    container.empty();
    container.addClass("memograph-diff-unified");
    const statsEl = container.createDiv({ cls: "diff-stats" });
    statsEl.createEl("span", {
      text: `${diff.stats.added} additions`,
      cls: "diff-stat-added"
    });
    statsEl.createEl("span", { text: " \xB7 " });
    statsEl.createEl("span", {
      text: `${diff.stats.removed} deletions`,
      cls: "diff-stat-removed"
    });
    statsEl.createEl("span", { text: " \xB7 " });
    statsEl.createEl("span", {
      text: `${diff.stats.modified} modifications`,
      cls: "diff-stat-modified"
    });
    const diffContent = container.createDiv({ cls: "diff-content-unified" });
    const allLines = this.mergeForUnifiedView(diff);
    allLines.forEach((line) => {
      const lineEl = diffContent.createDiv({ cls: `diff-line diff-line-${line.type}` });
      const lineNumber = lineEl.createEl("span", {
        cls: "diff-line-number",
        text: line.lineNumber > 0 ? String(line.lineNumber) : " "
      });
      const marker = lineEl.createEl("span", { cls: "diff-line-marker" });
      if (line.type === "added") {
        marker.textContent = "+ ";
      } else if (line.type === "removed") {
        marker.textContent = "- ";
      } else if (line.type === "modified") {
        marker.textContent = "~ ";
      } else {
        marker.textContent = "  ";
      }
      const content = lineEl.createEl("span", {
        cls: "diff-line-content",
        text: line.content
      });
    });
  }
  /**
   * Render side-by-side diff view
   */
  static renderSideBySideDiff(container, localText, remoteText) {
    const diff = this.computeDiff(localText, remoteText);
    container.empty();
    container.addClass("memograph-diff-sidebyside");
    const statsEl = container.createDiv({ cls: "diff-stats" });
    statsEl.createEl("span", {
      text: `${diff.stats.added} additions`,
      cls: "diff-stat-added"
    });
    statsEl.createEl("span", { text: " \xB7 " });
    statsEl.createEl("span", {
      text: `${diff.stats.removed} deletions`,
      cls: "diff-stat-removed"
    });
    statsEl.createEl("span", { text: " \xB7 " });
    statsEl.createEl("span", {
      text: `${diff.stats.modified} modifications`,
      cls: "diff-stat-modified"
    });
    const panelsContainer = container.createDiv({ cls: "diff-panels" });
    const localPanel = panelsContainer.createDiv({ cls: "diff-panel diff-panel-local" });
    localPanel.createEl("h4", { text: "Local (Obsidian)" });
    const localContent = localPanel.createDiv({ cls: "diff-content" });
    diff.localLines.forEach((line) => {
      const lineEl = localContent.createDiv({ cls: `diff-line diff-line-${line.type}` });
      lineEl.createEl("span", { cls: "diff-line-number", text: String(line.lineNumber) });
      lineEl.createEl("span", { cls: "diff-line-content", text: line.content || " " });
    });
    const remotePanel = panelsContainer.createDiv({ cls: "diff-panel diff-panel-remote" });
    remotePanel.createEl("h4", { text: "Remote (MemoGraph)" });
    const remoteContent = remotePanel.createDiv({ cls: "diff-content" });
    diff.remoteLines.forEach((line) => {
      const lineEl = remoteContent.createDiv({ cls: `diff-line diff-line-${line.type}` });
      lineEl.createEl("span", { cls: "diff-line-number", text: String(line.lineNumber) });
      lineEl.createEl("span", { cls: "diff-line-content", text: line.content || " " });
    });
  }
  /**
   * Merge diff lines for unified view
   */
  static mergeForUnifiedView(diff) {
    const merged = [];
    let localIdx = 0;
    let remoteIdx = 0;
    while (localIdx < diff.localLines.length || remoteIdx < diff.remoteLines.length) {
      const localLine = localIdx < diff.localLines.length ? diff.localLines[localIdx] : null;
      const remoteLine = remoteIdx < diff.remoteLines.length ? diff.remoteLines[remoteIdx] : null;
      if (!localLine) {
        merged.push({ ...remoteLine, side: "remote" });
        remoteIdx++;
      } else if (!remoteLine) {
        merged.push({ ...localLine, side: "local" });
        localIdx++;
      } else if (localLine.type === "unchanged" && remoteLine.type === "unchanged") {
        merged.push({ ...localLine, side: "local" });
        localIdx++;
        remoteIdx++;
      } else if (localLine.type === "modified" && remoteLine.type === "modified") {
        merged.push({ ...localLine, side: "local" });
        merged.push({ ...remoteLine, side: "remote" });
        localIdx++;
        remoteIdx++;
      } else {
        if (localLine.type === "removed") {
          merged.push({ ...localLine, side: "local" });
          localIdx++;
        }
        if (remoteLine.type === "added") {
          merged.push({ ...remoteLine, side: "remote" });
          remoteIdx++;
        }
      }
    }
    return merged;
  }
  /**
   * Add styles for diff view
   */
  static addStyles() {
    if (document.getElementById("memograph-diff-styles")) {
      return;
    }
    const styleEl = document.createElement("style");
    styleEl.id = "memograph-diff-styles";
    styleEl.textContent = `
            .memograph-diff-unified,
            .memograph-diff-sidebyside {
                font-family: var(--font-monospace);
                font-size: 0.85em;
            }

            .diff-stats {
                padding: 10px;
                background: var(--background-secondary);
                border-bottom: 1px solid var(--background-modifier-border);
                text-align: center;
            }

            .diff-stat-added {
                color: var(--text-success);
                font-weight: 600;
            }

            .diff-stat-removed {
                color: var(--text-error);
                font-weight: 600;
            }

            .diff-stat-modified {
                color: var(--text-warning);
                font-weight: 600;
            }

            .diff-content-unified {
                max-height: 400px;
                overflow-y: auto;
            }

            .diff-line {
                display: flex;
                padding: 2px 5px;
                line-height: 1.5;
            }

            .diff-line-number {
                display: inline-block;
                width: 40px;
                text-align: right;
                padding-right: 10px;
                color: var(--text-muted);
                user-select: none;
            }

            .diff-line-marker {
                width: 20px;
                font-weight: bold;
                user-select: none;
            }

            .diff-line-content {
                flex: 1;
                white-space: pre;
            }

            .diff-line-added {
                background: rgba(46, 160, 67, 0.15);
            }

            .diff-line-added .diff-line-marker {
                color: var(--text-success);
            }

            .diff-line-removed {
                background: rgba(248, 81, 73, 0.15);
            }

            .diff-line-removed .diff-line-marker {
                color: var(--text-error);
            }

            .diff-line-modified {
                background: rgba(219, 171, 9, 0.15);
            }

            .diff-line-modified .diff-line-marker {
                color: var(--text-warning);
            }

            .diff-line-unchanged {
                background: transparent;
            }

            .diff-panels {
                display: flex;
                gap: 2px;
                background: var(--background-modifier-border);
            }

            .diff-panel {
                flex: 1;
                background: var(--background-primary);
            }

            .diff-panel h4 {
                margin: 0;
                padding: 8px 10px;
                background: var(--background-secondary);
                border-bottom: 1px solid var(--background-modifier-border);
                font-size: 0.9em;
                font-weight: 600;
            }

            .diff-panel-local h4 {
                border-left: 3px solid var(--interactive-accent);
            }

            .diff-panel-remote h4 {
                border-left: 3px solid var(--text-accent);
            }

            .diff-panel .diff-content {
                max-height: 400px;
                overflow-y: auto;
            }
        `;
    document.head.appendChild(styleEl);
  }
};

// src/sync.ts
var SyncManager = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
    this.syncing = false;
    this.debounceTimers = /* @__PURE__ */ new Map();
    this.syncQueue = /* @__PURE__ */ new Set();
    this.conflictHistory = [];
    this.batchSyncing = false;
    this.batchCancelled = false;
    this.errorHistory = [];
    DiffView.addStyles();
  }
  async batchSync(options = {}) {
    if (this.batchSyncing) {
      new import_obsidian3.Notice("Batch sync already in progress");
      return {
        pulled: 0,
        pushed: 0,
        conflicts: 0,
        errors: ["Batch sync already in progress"],
        cancelled: false,
        processed: 0,
        duration: 0,
        timestamp: Date.now()
      };
    }
    const startTime = Date.now();
    this.batchSyncing = true;
    this.batchCancelled = false;
    const {
      batchSize = 50,
      direction = "bidirectional",
      onProgress
    } = options;
    const stats = {
      pulled: 0,
      pushed: 0,
      conflicts: 0,
      errors: [],
      cancelled: false,
      processed: 0,
      timestamp: startTime
    };
    try {
      const files = this.app.vault.getMarkdownFiles();
      const filteredFiles = this.filterFiles(files);
      const totalFiles = filteredFiles.length;
      if (totalFiles === 0) {
        new import_obsidian3.Notice("No files to sync");
        return stats;
      }
      new import_obsidian3.Notice(`Starting batch sync of ${totalFiles} files...`);
      for (let i = 0; i < totalFiles; i += batchSize) {
        if (this.batchCancelled) {
          stats.cancelled = true;
          new import_obsidian3.Notice("Batch sync cancelled");
          break;
        }
        const batch = filteredFiles.slice(i, Math.min(i + batchSize, totalFiles));
        if (direction === "pull" || direction === "bidirectional") {
          if (onProgress) {
            onProgress(i + batch.length, totalFiles, "Pulling...", "pull");
          }
        }
        if (direction === "push" || direction === "bidirectional") {
          for (let j = 0; j < batch.length; j++) {
            if (this.batchCancelled) {
              break;
            }
            const file = batch[j];
            const currentIndex = i + j + 1;
            if (onProgress) {
              onProgress(currentIndex, totalFiles, file.path, "pushing");
            }
            try {
              await this.syncFile(file);
              stats.pushed++;
              stats.processed = (stats.processed || 0) + 1;
            } catch (error) {
              stats.errors.push(`Error syncing ${file.path}: ${error}`);
            }
          }
        }
        await new Promise((resolve) => setTimeout(resolve, 100));
      }
      const duration = Date.now() - startTime;
      stats.duration = duration;
      if (!stats.cancelled) {
        new import_obsidian3.Notice(
          `Batch sync complete: \u2193${stats.pulled} \u2191${stats.pushed} \u26A0${stats.conflicts} conflicts (${(duration / 1e3).toFixed(1)}s)`
        );
      }
    } catch (error) {
      stats.errors.push(`Batch sync failed: ${error}`);
      new import_obsidian3.Notice(`Batch sync failed: ${error}`);
    } finally {
      this.batchSyncing = false;
      stats.duration = Date.now() - startTime;
    }
    return stats;
  }
  async batchSyncWithProgress() {
    let progressNotice = null;
    const stats = await this.batchSync({
      batchSize: 50,
      direction: "bidirectional",
      onProgress: (current, total, file, status) => {
        const percentage = Math.round(current / total * 100);
        const message = `Syncing ${current}/${total} (${percentage}%) - ${status}: ${file}`;
        if (progressNotice) {
          progressNotice.setMessage(message);
        } else {
          progressNotice = new import_obsidian3.Notice(message, 0);
        }
      }
    });
    if (progressNotice) {
      progressNotice.hide();
    }
    return stats;
  }
  cancelBatchSync() {
    if (this.batchSyncing) {
      this.batchCancelled = true;
      new import_obsidian3.Notice("Cancelling batch sync...");
    }
  }
  getBatchSyncStatus() {
    return {
      syncing: this.batchSyncing,
      cancelled: this.batchCancelled
    };
  }
  async sync() {
    if (this.syncing) {
      new import_obsidian3.Notice("Sync already in progress");
      return {
        pulled: 0,
        pushed: 0,
        conflicts: 0,
        errors: ["Sync already in progress"],
        duration: 0,
        timestamp: Date.now()
      };
    }
    const startTime = Date.now();
    this.syncing = true;
    const stats = {
      pulled: 0,
      pushed: 0,
      conflicts: 0,
      errors: [],
      timestamp: startTime
    };
    try {
      new import_obsidian3.Notice("Starting bidirectional sync with MemoGraph...");
      try {
        const pullStats = await this.pullFromMemoGraph();
        stats.pulled = pullStats.pulled;
        stats.conflicts += pullStats.conflicts;
        stats.errors.push(...pullStats.errors);
      } catch (error) {
        stats.errors.push(`Pull failed: ${error}`);
      }
      const files = this.app.vault.getMarkdownFiles();
      const filteredFiles = this.filterFiles(files);
      for (const file of filteredFiles) {
        try {
          await this.syncFile(file);
          stats.pushed++;
        } catch (error) {
          stats.errors.push(`Error syncing ${file.path}: ${error}`);
        }
      }
      const duration = Date.now() - startTime;
      stats.duration = duration;
      if (stats.errors.length === 0) {
        new import_obsidian3.Notice(`Sync complete: \u2193${stats.pulled} \u2191${stats.pushed} (${(duration / 1e3).toFixed(1)}s)`);
      } else {
        new import_obsidian3.Notice(`Sync completed with ${stats.errors.length} errors`);
      }
    } catch (error) {
      stats.errors.push(`Sync failed: ${error}`);
      new import_obsidian3.Notice(`Sync failed: ${error}`);
    } finally {
      this.syncing = false;
      stats.duration = Date.now() - startTime;
    }
    return stats;
  }
  async syncFileDebounced(file) {
    const filePath = file.path;
    if (this.debounceTimers.has(filePath)) {
      clearTimeout(this.debounceTimers.get(filePath));
    }
    const timer = setTimeout(async () => {
      this.debounceTimers.delete(filePath);
      this.syncQueue.delete(filePath);
      try {
        await this.syncFile(file);
      } catch (error) {
        new import_obsidian3.Notice(`Failed to sync ${file.basename}: ${error}`);
      }
    }, this.settings.debounceDelay);
    this.debounceTimers.set(filePath, timer);
    this.syncQueue.add(filePath);
  }
  async syncFile(file) {
    var _a;
    const content = await this.app.vault.read(file);
    const metadata = this.app.metadataCache.getFileCache(file);
    const frontmatter = (metadata == null ? void 0 : metadata.frontmatter) || {};
    const tags = ((_a = metadata == null ? void 0 : metadata.tags) == null ? void 0 : _a.map((t) => t.tag)) || [];
    const data = {
      title: frontmatter.title || file.basename,
      content,
      tags: [...tags, ...frontmatter.tags || []],
      metadata: {
        ...frontmatter,
        source: "obsidian",
        path: file.path,
        modified: file.stat.mtime
      }
    };
    await this.pushToMemoGraph(data);
  }
  async pushToMemoGraph(data) {
    const operation = async () => {
      const url = `${this.settings.memoGraphUrl}/api/memories`;
      const headers = {
        "Content-Type": "application/json"
      };
      if (this.settings.apiKey) {
        headers["Authorization"] = `Bearer ${this.settings.apiKey}`;
      }
      const response = await fetch(url, {
        method: "POST",
        headers,
        body: JSON.stringify(data)
      });
      if (!response.ok) {
        throw new Error(`MemoGraph API error: ${response.statusText}`);
      }
    };
    await this.retryWithBackoff(operation, 3, 1e3);
  }
  async pullFromMemoGraph() {
    const stats = {
      pulled: 0,
      pushed: 0,
      conflicts: 0,
      errors: []
    };
    try {
      const memories = await this.fetchMemoriesFromMemoGraph();
      for (const memory of memories) {
        try {
          await this.saveMemoryToVault(memory);
          stats.pulled++;
        } catch (error) {
          stats.errors.push(`Error pulling memory ${memory.id}: ${error}`);
        }
      }
    } catch (error) {
      stats.errors.push(`Failed to fetch memories: ${error}`);
      throw error;
    }
    return stats;
  }
  async fetchMemoriesFromMemoGraph() {
    const operation = async () => {
      const url = `${this.settings.memoGraphUrl}/api/memories`;
      const headers = {
        "Content-Type": "application/json"
      };
      if (this.settings.apiKey) {
        headers["Authorization"] = `Bearer ${this.settings.apiKey}`;
      }
      const response = await fetch(url, {
        method: "GET",
        headers
      });
      if (!response.ok) {
        throw new Error(`MemoGraph API error: ${response.statusText}`);
      }
      const data = await response.json();
      return data.memories || [];
    };
    return await this.retryWithBackoff(operation, 3, 1e3);
  }
  async saveMemoryToVault(memory) {
    var _a, _b;
    const filePath = ((_a = memory.metadata) == null ? void 0 : _a.path) || `${memory.title || memory.id}.md`;
    const existingFile = this.app.vault.getAbstractFileByPath(filePath);
    const markdownContent = this.memoryToMarkdown(memory);
    if (existingFile instanceof import_obsidian3.TFile) {
      const currentContent = await this.app.vault.read(existingFile);
      if (currentContent !== markdownContent) {
        const resolvedContent = await this.handleConflict(
          filePath,
          currentContent,
          markdownContent,
          existingFile.stat.mtime,
          ((_b = memory.metadata) == null ? void 0 : _b.modified) || Date.now()
        );
        if (resolvedContent !== null) {
          await this.app.vault.modify(existingFile, resolvedContent);
        }
      }
    } else {
      const parentPath = filePath.substring(0, filePath.lastIndexOf("/"));
      if (parentPath && !this.app.vault.getAbstractFileByPath(parentPath)) {
        await this.createFolderPath(parentPath);
      }
      await this.app.vault.create(filePath, markdownContent);
    }
  }
  async handleConflict(filePath, localContent, remoteContent, localModified, remoteModified) {
    if (this.settings.conflictStrategy !== "manual") {
      let resolvedContent = null;
      let resolution = "keep-local";
      switch (this.settings.conflictStrategy) {
        case "obsidian_wins":
          resolvedContent = localContent;
          resolution = "keep-local";
          break;
        case "memograph_wins":
          resolvedContent = remoteContent;
          resolution = "keep-remote";
          break;
        case "newest_wins":
          resolvedContent = localModified > remoteModified ? localContent : remoteContent;
          resolution = localModified > remoteModified ? "keep-local" : "keep-remote";
          break;
      }
      this.conflictHistory.push({
        filePath,
        timestamp: Date.now(),
        resolution,
        autoResolved: true
      });
      new import_obsidian3.Notice(`Conflict auto-resolved: ${filePath} (${resolution})`);
      return resolvedContent;
    }
    return new Promise((resolve) => {
      const conflictData = {
        filePath,
        localVersion: localContent,
        remoteVersion: remoteContent,
        localModified,
        remoteModified
      };
      const modal = new ConflictModal(
        this.app,
        conflictData,
        (resolution, mergedContent) => {
          let resolvedContent = null;
          switch (resolution) {
            case "keep-local":
              resolvedContent = localContent;
              break;
            case "keep-remote":
              resolvedContent = remoteContent;
              break;
            case "keep-both":
              resolvedContent = mergedContent || this.createMergedContent(
                localContent,
                remoteContent,
                localModified,
                remoteModified
              );
              break;
            case "manual":
              resolvedContent = this.createMergedContent(
                localContent,
                remoteContent,
                localModified,
                remoteModified
              );
              new import_obsidian3.Notice("Conflict markers added. Please resolve manually.");
              break;
          }
          this.conflictHistory.push({
            filePath,
            timestamp: Date.now(),
            resolution,
            autoResolved: false
          });
          resolve(resolvedContent);
        }
      );
      modal.open();
    });
  }
  createMergedContent(localContent, remoteContent, localModified, remoteModified) {
    return `<<<<<<< Local Version (${new Date(localModified).toLocaleString()})
${localContent}
=======
${remoteContent}
>>>>>>> Remote Version (MemoGraph) (${new Date(remoteModified).toLocaleString()})
`;
  }
  getConflictHistory() {
    return this.conflictHistory;
  }
  clearConflictHistory() {
    this.conflictHistory = [];
  }
  memoryToMarkdown(memory) {
    var _a;
    const frontmatter = {
      title: memory.title || ((_a = memory.metadata) == null ? void 0 : _a.title) || "Untitled",
      tags: memory.tags || [],
      ...memory.metadata
    };
    delete frontmatter.path;
    delete frontmatter.source;
    let markdown = "---\n";
    for (const [key, value] of Object.entries(frontmatter)) {
      if (Array.isArray(value)) {
        markdown += `${key}: [${value.join(", ")}]
`;
      } else if (typeof value === "string") {
        markdown += `${key}: ${value}
`;
      } else {
        markdown += `${key}: ${JSON.stringify(value)}
`;
      }
    }
    markdown += "---\n\n";
    markdown += memory.content || "";
    return markdown;
  }
  async createFolderPath(path) {
    const parts = path.split("/");
    let currentPath = "";
    for (const part of parts) {
      currentPath = currentPath ? `${currentPath}/${part}` : part;
      const folder = this.app.vault.getAbstractFileByPath(currentPath);
      if (!folder) {
        await this.app.vault.createFolder(currentPath);
      }
    }
  }
  filterFiles(files) {
    return files.filter((file) => {
      var _a, _b;
      for (const folder of this.settings.excludedFolders) {
        if (file.path.startsWith(folder + "/") || file.path === folder) {
          return false;
        }
      }
      if (this.settings.includedTags.length > 0) {
        const metadata = this.app.metadataCache.getFileCache(file);
        const tags = ((_a = metadata == null ? void 0 : metadata.tags) == null ? void 0 : _a.map((t) => t.tag)) || [];
        const frontmatterTags = ((_b = metadata == null ? void 0 : metadata.frontmatter) == null ? void 0 : _b.tags) || [];
        const allTags = [...tags, ...frontmatterTags];
        const hasIncludedTag = this.settings.includedTags.some(
          (includedTag) => allTags.some((tag) => tag.includes(includedTag))
        );
        if (!hasIncludedTag) {
          return false;
        }
      }
      return true;
    });
  }
  getSyncQueueStatus() {
    return {
      queued: this.syncQueue.size,
      syncing: this.syncing,
      queuedFiles: Array.from(this.syncQueue)
    };
  }
  cancelAllPendingSyncs() {
    for (const timer of this.debounceTimers.values()) {
      clearTimeout(timer);
    }
    this.debounceTimers.clear();
    this.syncQueue.clear();
  }
  /**
   * Retry an operation with exponential backoff
   * @param operation - Async operation to retry
   * @param maxAttempts - Maximum number of retry attempts (default: 3)
   * @param initialDelay - Initial delay in milliseconds (default: 1000)
   * @returns Result of the operation
   */
  async retryWithBackoff(operation, maxAttempts = 3, initialDelay = 1e3) {
    let lastError = null;
    let delay = initialDelay;
    for (let attempt = 1; attempt <= maxAttempts; attempt++) {
      try {
        return await operation();
      } catch (error) {
        lastError = error;
        this.recordError(lastError, attempt < maxAttempts);
        if (!this.isRetryableError(lastError)) {
          throw lastError;
        }
        if (attempt < maxAttempts) {
          await this.sleep(delay);
          delay *= 2;
        }
      }
    }
    throw lastError;
  }
  /**
   * Check if an error is retryable (transient)
   * @param error - Error to check
   * @returns True if error is retryable
   */
  isRetryableError(error) {
    const message = error.message.toLowerCase();
    if (message.includes("network") || message.includes("timeout") || message.includes("connection") || message.includes("econnrefused") || message.includes("enotfound")) {
      return true;
    }
    if (message.includes("503") || // Service Unavailable
    message.includes("504") || // Gateway Timeout
    message.includes("429")) {
      return true;
    }
    return false;
  }
  /**
   * Sleep for a specified duration
   * @param ms - Duration in milliseconds
   */
  sleep(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
  /**
   * Record an error in the error history
   * @param error - Error to record
   * @param willRetry - Whether the operation will be retried
   */
  recordError(error, willRetry) {
    const errorEntry = {
      timestamp: Date.now(),
      message: error.message,
      type: error.name,
      willRetry
    };
    this.errorHistory.push(errorEntry);
    if (this.errorHistory.length > 100) {
      this.errorHistory = this.errorHistory.slice(-100);
    }
    if (willRetry) {
      console.warn(`Sync error (will retry): ${error.message}`);
    } else {
      console.error(`Sync error (permanent): ${error.message}`);
    }
  }
  /**
   * Get error history
   * @returns Array of error entries
   */
  getErrorHistory() {
    return [...this.errorHistory];
  }
  /**
   * Clear error history
   * @returns Number of errors cleared
   */
  clearErrorHistory() {
    const count = this.errorHistory.length;
    this.errorHistory = [];
    return count;
  }
};

// src/syncStats.ts
var SyncStatsManager = class {
  constructor(storageKey = "memograph-sync-stats", maxHistorySize = 50) {
    this.storageKey = storageKey;
    this.maxHistorySize = maxHistorySize;
    this.stats = this.getDefaultStats();
    this.history = [];
    this.loadFromStorage();
  }
  getDefaultStats() {
    return {
      totalSyncs: 0,
      lastSyncTime: null,
      successfulSyncs: 0,
      failedSyncs: 0,
      filesPulled: 0,
      filesPushed: 0,
      conflictsResolved: 0,
      totalErrors: 0,
      averageSyncDuration: 0,
      lastSyncDuration: 0,
      lastSyncStats: null
    };
  }
  recordSyncStart(direction) {
    return Date.now();
  }
  recordSyncEnd(startTime, direction, pulled, pushed, conflicts, errors, cancelled = false) {
    const endTime = Date.now();
    const duration = endTime - startTime;
    const status = cancelled ? "cancelled" : errors.length > 0 ? "failed" : "success";
    this.stats.totalSyncs++;
    this.stats.lastSyncTime = endTime;
    this.stats.lastSyncDuration = duration;
    this.stats.filesPulled += pulled;
    this.stats.filesPushed += pushed;
    this.stats.conflictsResolved += conflicts;
    this.stats.totalErrors += errors.length;
    if (status === "success") {
      this.stats.successfulSyncs++;
    } else if (status === "failed") {
      this.stats.failedSyncs++;
    }
    this.stats.averageSyncDuration = (this.stats.averageSyncDuration * (this.stats.totalSyncs - 1) + duration) / this.stats.totalSyncs;
    this.stats.lastSyncStats = {
      pulled,
      pushed,
      conflicts,
      errors,
      timestamp: endTime,
      duration
    };
    const historyEntry = {
      timestamp: endTime,
      direction,
      pulled,
      pushed,
      conflicts,
      errors,
      duration,
      status
    };
    this.history.unshift(historyEntry);
    if (this.history.length > this.maxHistorySize) {
      this.history = this.history.slice(0, this.maxHistorySize);
    }
    this.saveToStorage();
  }
  getStatistics() {
    return { ...this.stats };
  }
  getHistory(limit) {
    if (limit) {
      return this.history.slice(0, limit);
    }
    return [...this.history];
  }
  getRecentErrors(limit = 10) {
    const errors = [];
    for (const entry of this.history) {
      if (entry.errors.length > 0) {
        errors.push(...entry.errors.map((e) => `[${new Date(entry.timestamp).toLocaleString()}] ${e}`));
        if (errors.length >= limit) {
          break;
        }
      }
    }
    return errors.slice(0, limit);
  }
  clearHistory() {
    this.history = [];
    this.saveToStorage();
  }
  resetStatistics() {
    this.stats = this.getDefaultStats();
    this.history = [];
    this.saveToStorage();
  }
  loadFromStorage() {
    try {
      const stored = localStorage.getItem(this.storageKey);
      if (stored) {
        const data = JSON.parse(stored);
        this.stats = data.stats || this.getDefaultStats();
        this.history = data.history || [];
      }
    } catch (error) {
      console.error("Failed to load sync stats from storage:", error);
    }
  }
  saveToStorage() {
    try {
      const data = {
        stats: this.stats,
        history: this.history
      };
      localStorage.setItem(this.storageKey, JSON.stringify(data));
    } catch (error) {
      console.error("Failed to save sync stats to storage:", error);
    }
  }
  getSuccessRate() {
    if (this.stats.totalSyncs === 0)
      return 0;
    return this.stats.successfulSyncs / this.stats.totalSyncs * 100;
  }
  getAverageFilesPerSync() {
    if (this.stats.totalSyncs === 0) {
      return { pulled: 0, pushed: 0 };
    }
    return {
      pulled: this.stats.filesPulled / this.stats.totalSyncs,
      pushed: this.stats.filesPushed / this.stats.totalSyncs
    };
  }
  formatDuration(ms) {
    if (ms < 1e3)
      return `${ms}ms`;
    if (ms < 6e4)
      return `${(ms / 1e3).toFixed(1)}s`;
    const minutes = Math.floor(ms / 6e4);
    const seconds = (ms % 6e4 / 1e3).toFixed(0);
    return `${minutes}m ${seconds}s`;
  }
};

// src/statusView.ts
var import_obsidian4 = require("obsidian");
var STATUS_VIEW_TYPE = "memograph-status-view";
var StatusView = class extends import_obsidian4.ItemView {
  constructor(leaf, statsManager, syncManager) {
    super(leaf);
    this.refreshInterval = null;
    this.container = null;
    this.statsManager = statsManager;
    this.syncManager = syncManager;
  }
  getViewType() {
    return STATUS_VIEW_TYPE;
  }
  getDisplayText() {
    return "MemoGraph Sync Status";
  }
  getIcon() {
    return "sync";
  }
  async onOpen() {
    this.container = this.containerEl.children[1];
    this.container.empty();
    this.container.addClass("memograph-status-view");
    this.render();
    this.refreshInterval = window.setInterval(() => {
      this.render();
    }, 5e3);
  }
  async onClose() {
    if (this.refreshInterval !== null) {
      window.clearInterval(this.refreshInterval);
      this.refreshInterval = null;
    }
  }
  refresh() {
    this.render();
  }
  render() {
    if (!this.container)
      return;
    this.container.empty();
    this.addStyles();
    this.renderCurrentStatus();
    this.renderStatistics();
    this.renderHistory();
    this.renderErrors();
    this.renderActions();
  }
  addStyles() {
    const styleId = "memograph-status-styles";
    if (document.getElementById(styleId))
      return;
    const style = document.createElement("style");
    style.id = styleId;
    style.textContent = `
            .memograph-status-view {
                padding: 20px;
                overflow-y: auto;
            }
            .status-section {
                margin-bottom: 20px;
                padding: 15px;
                border: 1px solid var(--background-modifier-border);
                border-radius: 5px;
            }
            .status-section h3 {
                margin-top: 0;
                margin-bottom: 10px;
                color: var(--text-accent);
            }
            .status-row {
                display: flex;
                justify-content: space-between;
                padding: 5px 0;
                border-bottom: 1px solid var(--background-modifier-border);
            }
            .status-row:last-child {
                border-bottom: none;
            }
            .status-label {
                font-weight: 500;
            }
            .status-value {
                color: var(--text-muted);
            }
            .status-badge {
                display: inline-block;
                padding: 2px 8px;
                border-radius: 3px;
                font-size: 0.9em;
                font-weight: 500;
            }
            .status-badge.success {
                background-color: var(--background-modifier-success);
                color: var(--text-on-accent);
            }
            .status-badge.error {
                background-color: var(--background-modifier-error);
                color: var(--text-on-accent);
            }
            .status-badge.syncing {
                background-color: var(--interactive-accent);
                color: var(--text-on-accent);
            }
            .status-badge.idle {
                background-color: var(--background-modifier-border);
                color: var(--text-normal);
            }
            .progress-bar {
                width: 100%;
                height: 20px;
                background-color: var(--background-modifier-border);
                border-radius: 10px;
                overflow: hidden;
                margin: 10px 0;
            }
            .progress-fill {
                height: 100%;
                background-color: var(--interactive-accent);
                transition: width 0.3s ease;
                display: flex;
                align-items: center;
                justify-content: center;
                color: var(--text-on-accent);
                font-size: 0.8em;
                font-weight: 500;
            }
            .history-entry {
                padding: 8px;
                margin: 5px 0;
                background-color: var(--background-secondary);
                border-radius: 3px;
            }
            .history-timestamp {
                font-size: 0.85em;
                color: var(--text-muted);
            }
            .error-entry {
                padding: 8px;
                margin: 5px 0;
                background-color: var(--background-modifier-error);
                border-radius: 3px;
                font-size: 0.9em;
            }
            .action-buttons {
                display: flex;
                gap: 10px;
                flex-wrap: wrap;
            }
            .action-button {
                padding: 8px 15px;
                background-color: var(--interactive-accent);
                color: var(--text-on-accent);
                border: none;
                border-radius: 3px;
                cursor: pointer;
                font-size: 0.9em;
            }
            .action-button:hover {
                opacity: 0.8;
            }
            .action-button.secondary {
                background-color: var(--background-modifier-border);
                color: var(--text-normal);
            }
        `;
    document.head.appendChild(style);
  }
  renderCurrentStatus() {
    const section = this.container.createDiv({ cls: "status-section" });
    section.createEl("h3", { text: "Current Status" });
    const queueStatus = this.syncManager.getSyncQueueStatus();
    const batchStatus = this.syncManager.getBatchSyncStatus();
    const isSyncing = queueStatus.syncing || batchStatus.syncing;
    const statusRow = section.createDiv({ cls: "status-row" });
    statusRow.createSpan({ cls: "status-label", text: "Status:" });
    let badgeText = "Idle";
    let badgeClass = "idle";
    if (isSyncing) {
      badgeText = "Syncing";
      badgeClass = "syncing";
    } else if (queueStatus.queued > 0) {
      badgeText = `${queueStatus.queued} Queued`;
      badgeClass = "idle";
    }
    const badge = statusRow.createSpan({
      cls: `status-badge ${badgeClass}`,
      text: badgeText
    });
    if (queueStatus.queued > 0) {
      const queueRow = section.createDiv({ cls: "status-row" });
      queueRow.createSpan({ cls: "status-label", text: "Queued Files:" });
      queueRow.createSpan({
        cls: "status-value",
        text: queueStatus.queued.toString()
      });
      const fileList = queueStatus.queuedFiles.slice(0, 5);
      if (fileList.length > 0) {
        const filesDiv = section.createDiv({ cls: "status-row" });
        filesDiv.createSpan({ cls: "status-label", text: "Files:" });
        const fileNames = filesDiv.createDiv({ cls: "status-value" });
        fileList.forEach((file) => {
          fileNames.createEl("div", {
            text: `\u2022 ${file.split("/").pop()}`,
            cls: "file-name"
          });
        });
        if (queueStatus.queued > 5) {
          fileNames.createEl("div", {
            text: `... and ${queueStatus.queued - 5} more`,
            cls: "file-name"
          });
        }
      }
    }
    const stats = this.statsManager.getStatistics();
    if (stats.lastSyncTime) {
      const lastSyncRow = section.createDiv({ cls: "status-row" });
      lastSyncRow.createSpan({ cls: "status-label", text: "Last Sync:" });
      lastSyncRow.createSpan({
        cls: "status-value",
        text: new Date(stats.lastSyncTime).toLocaleString()
      });
    }
  }
  formatTimestamp(timestamp) {
    const now = Date.now();
    const diff = now - timestamp;
    if (diff < 6e4)
      return "Just now";
    if (diff < 36e5)
      return `${Math.floor(diff / 6e4)} minutes ago`;
    if (diff < 864e5)
      return `${Math.floor(diff / 36e5)} hours ago`;
    return new Date(timestamp).toLocaleString();
  }
  renderStatistics() {
    const section = this.container.createDiv({ cls: "status-section" });
    section.createEl("h3", { text: "Statistics" });
    const stats = this.statsManager.getStatistics();
    const averages = this.statsManager.getAverageFilesPerSync();
    const successRate = this.statsManager.getSuccessRate();
    const rows = [
      { label: "Total Syncs", value: stats.totalSyncs.toString() },
      { label: "Successful", value: stats.successfulSyncs.toString() },
      { label: "Failed", value: stats.failedSyncs.toString() },
      { label: "Success Rate", value: `${successRate.toFixed(1)}%` },
      { label: "Files Pulled", value: stats.filesPulled.toString() },
      { label: "Files Pushed", value: stats.filesPushed.toString() },
      { label: "Conflicts Resolved", value: stats.conflictsResolved.toString() },
      { label: "Total Errors", value: stats.totalErrors.toString() },
      {
        label: "Avg. Duration",
        value: this.statsManager.formatDuration(stats.averageSyncDuration)
      },
      {
        label: "Avg. Files/Sync",
        value: `\u2193${averages.pulled.toFixed(1)} \u2191${averages.pushed.toFixed(1)}`
      }
    ];
    rows.forEach((row) => {
      const rowEl = section.createDiv({ cls: "status-row" });
      rowEl.createSpan({ cls: "status-label", text: row.label + ":" });
      rowEl.createSpan({ cls: "status-value", text: row.value });
    });
    if (stats.totalSyncs > 0) {
      section.createEl("div", { text: "Success Rate", cls: "status-label" });
      const progressBar = section.createDiv({ cls: "progress-bar" });
      const progressFill = progressBar.createDiv({ cls: "progress-fill" });
      progressFill.style.width = `${successRate}%`;
      progressFill.setText(`${successRate.toFixed(1)}%`);
    }
  }
  renderHistory() {
    const section = this.container.createDiv({ cls: "status-section" });
    section.createEl("h3", { text: "Recent Sync History" });
    const history = this.statsManager.getHistory(10);
    if (history.length === 0) {
      section.createDiv({
        cls: "status-value",
        text: "No sync history available"
      });
      return;
    }
    history.forEach((entry) => {
      const entryDiv = section.createDiv({ cls: "history-entry" });
      const timestampDiv = entryDiv.createDiv({ cls: "history-timestamp" });
      timestampDiv.setText(new Date(entry.timestamp).toLocaleString());
      const statusBadge = entryDiv.createSpan({
        cls: `status-badge ${entry.status === "success" ? "success" : "error"}`,
        text: entry.status.toUpperCase()
      });
      const detailsDiv = entryDiv.createDiv();
      detailsDiv.setText(
        `${entry.direction.toUpperCase()} - \u2193${entry.pulled} \u2191${entry.pushed} \u26A0${entry.conflicts} conflicts (${this.statsManager.formatDuration(entry.duration)})`
      );
      if (entry.errors.length > 0) {
        const errorsDiv = entryDiv.createDiv({ cls: "error-entry" });
        errorsDiv.setText(`Errors: ${entry.errors.length}`);
      }
    });
  }
  renderErrors() {
    const recentErrors = this.statsManager.getRecentErrors(5);
    if (recentErrors.length === 0)
      return;
    const section = this.container.createDiv({ cls: "status-section" });
    section.createEl("h3", { text: "Recent Errors" });
    recentErrors.forEach((error) => {
      const errorDiv = section.createDiv({ cls: "error-entry" });
      errorDiv.setText(error);
    });
  }
  renderActions() {
    const section = this.container.createDiv({ cls: "status-section" });
    section.createEl("h3", { text: "Actions" });
    const buttonsDiv = section.createDiv({ cls: "action-buttons" });
    const refreshBtn = buttonsDiv.createEl("button", {
      cls: "action-button",
      text: "Refresh"
    });
    refreshBtn.addEventListener("click", () => {
      this.refresh();
      new import_obsidian4.Notice("Status refreshed");
    });
    const clearHistoryBtn = buttonsDiv.createEl("button", {
      cls: "action-button secondary",
      text: "Clear History"
    });
    clearHistoryBtn.addEventListener("click", () => {
      this.statsManager.clearHistory();
      this.refresh();
      new import_obsidian4.Notice("Sync history cleared");
    });
    const resetStatsBtn = buttonsDiv.createEl("button", {
      cls: "action-button secondary",
      text: "Reset Statistics"
    });
    resetStatsBtn.addEventListener("click", () => {
      this.statsManager.resetStatistics();
      this.refresh();
      new import_obsidian4.Notice("Statistics reset");
    });
    const batchStatus = this.syncManager.getBatchSyncStatus();
    if (batchStatus.syncing) {
      const cancelBtn = buttonsDiv.createEl("button", {
        cls: "action-button secondary",
        text: "Cancel Batch Sync"
      });
      cancelBtn.addEventListener("click", () => {
        this.syncManager.cancelBatchSync();
        new import_obsidian4.Notice("Cancelling batch sync...");
        setTimeout(() => this.refresh(), 1e3);
      });
    }
  }
};

// src/main.ts
var MemoGraphPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.syncIntervalId = null;
  }
  async onload() {
    console.log("Loading MemoGraph plugin");
    await this.loadSettings();
    this.statsManager = new SyncStatsManager();
    this.syncManager = new SyncManager(this.app, this.settings);
    this.registerView(
      STATUS_VIEW_TYPE,
      (leaf) => new StatusView(leaf, this.statsManager, this.syncManager)
    );
    this.addRibbonIcon("sync", "Sync with MemoGraph", async () => {
      const startTime = this.statsManager.recordSyncStart("bidirectional");
      new import_obsidian5.Notice("Syncing with MemoGraph...");
      const stats = await this.syncManager.sync();
      this.statsManager.recordSyncEnd(
        startTime,
        "bidirectional",
        stats.pulled,
        stats.pushed,
        stats.conflicts,
        stats.errors
      );
      new import_obsidian5.Notice("Sync complete!");
      this.refreshStatusView();
    });
    this.addCommand({
      id: "sync-memograph",
      name: "Sync with MemoGraph",
      callback: async () => {
        const startTime = this.statsManager.recordSyncStart("bidirectional");
        new import_obsidian5.Notice("Syncing with MemoGraph...");
        const stats = await this.syncManager.sync();
        this.statsManager.recordSyncEnd(
          startTime,
          "bidirectional",
          stats.pulled,
          stats.pushed,
          stats.conflicts,
          stats.errors
        );
        new import_obsidian5.Notice(`Sync complete: \u2193${stats.pulled} \u2191${stats.pushed}`);
        this.refreshStatusView();
      }
    });
    this.addCommand({
      id: "open-sync-status",
      name: "Open Sync Status Dashboard",
      callback: () => {
        this.activateStatusView();
      }
    });
    this.addCommand({
      id: "batch-sync",
      name: "Batch Sync All Files",
      callback: async () => {
        const startTime = this.statsManager.recordSyncStart("bidirectional");
        const stats = await this.syncManager.batchSyncWithProgress();
        this.statsManager.recordSyncEnd(
          startTime,
          "bidirectional",
          stats.pulled || 0,
          stats.pushed || 0,
          stats.conflicts || 0,
          stats.errors || [],
          stats.cancelled || false
        );
        this.refreshStatusView();
      }
    });
    this.addCommand({
      id: "view-conflict-history",
      name: "View Conflict History",
      callback: () => {
        const history = this.syncManager.getConflictHistory();
        if (history.length === 0) {
          new import_obsidian5.Notice("No conflicts recorded");
        } else {
          const summary = history.map(
            (c, i) => `${i + 1}. ${c.filePath} - ${c.resolution} (${c.autoResolved ? "auto" : "manual"})`
          ).join("\n");
          new import_obsidian5.Notice(`Conflict History:
${summary}`, 1e4);
        }
      }
    });
    this.addCommand({
      id: "clear-conflict-history",
      name: "Clear Conflict History",
      callback: () => {
        this.syncManager.clearConflictHistory();
        new import_obsidian5.Notice("Conflict history cleared");
      }
    });
    this.addSettingTab(new MemoGraphSettingTab(this.app, this));
    if (this.settings.autoSync) {
      this.enableAutoSync();
    }
  }
  async onunload() {
    console.log("Unloading MemoGraph plugin");
    this.disableAutoSync();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    if (this.settings.autoSync) {
      this.enableAutoSync();
    } else {
      this.disableAutoSync();
    }
  }
  enableAutoSync() {
    this.disableAutoSync();
    this.syncIntervalId = window.setInterval(
      async () => {
        console.log("Auto-syncing with MemoGraph...");
        await this.syncManager.sync();
      },
      this.settings.syncInterval * 1e3
    );
    this.registerEvent(
      this.app.vault.on("modify", async (file) => {
        if (file instanceof import_obsidian5.TFile && file.extension === "md") {
          await this.syncManager.syncFile(file);
        }
      })
    );
  }
  disableAutoSync() {
    if (this.syncIntervalId !== null) {
      window.clearInterval(this.syncIntervalId);
      this.syncIntervalId = null;
    }
  }
  async activateStatusView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(STATUS_VIEW_TYPE);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({ type: STATUS_VIEW_TYPE, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  refreshStatusView() {
    const leaves = this.app.workspace.getLeavesOfType(STATUS_VIEW_TYPE);
    leaves.forEach((leaf) => {
      const view = leaf.view;
      if (view instanceof StatusView) {
        view.refresh();
      }
    });
  }
};
