#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Set up a Git pre-push hook to automatically run CI checks before pushing.

.DESCRIPTION
    This script creates a Git pre-push hook that runs the local CI checks script
    before allowing a push. This helps catch issues before they reach GitHub Actions.

.PARAMETER Force
    Overwrite existing pre-push hook if it exists.

.PARAMETER Remove
    Remove the pre-push hook.

.EXAMPLE
    .\scripts\setup_pre_push_hook.ps1
    Install the pre-push hook

.EXAMPLE
    .\scripts\setup_pre_push_hook.ps1 -Force
    Install the pre-push hook, overwriting any existing hook

.EXAMPLE
    .\scripts\setup_pre_push_hook.ps1 -Remove
    Remove the pre-push hook

.NOTES
    The hook will run .\scripts\run_ci_locally.ps1 before each push.
    If checks fail, the push will be aborted.
#>

[CmdletBinding()]
param(
    [Parameter(HelpMessage="Overwrite existing pre-push hook")]
    [switch]$Force,

    [Parameter(HelpMessage="Remove the pre-push hook")]
    [switch]$Remove
)

# Color output functions
function Write-Success {
    param([string]$Message)
    Write-Host "✓ $Message" -ForegroundColor Green
}

function Write-Failure {
    param([string]$Message)
    Write-Host "✗ $Message" -ForegroundColor Red
}

function Write-Info {
    param([string]$Message)
    Write-Host "ℹ $Message" -ForegroundColor Cyan
}

function Write-Warning {
    param([string]$Message)
    Write-Host "⚠ $Message" -ForegroundColor Yellow
}

# Check if we're in a Git repository
if (-not (Test-Path ".git")) {
    Write-Failure "Not in a Git repository. Please run from the project root."
    exit 1
}

$hooksDir = ".git\hooks"
$hookPath = Join-Path $hooksDir "pre-push"
$hookPathPs1 = Join-Path $hooksDir "pre-push.ps1"

# Remove hook if requested
if ($Remove) {
    Write-Info "Removing pre-push hook..."

    $removed = $false
    if (Test-Path $hookPath) {
        Remove-Item $hookPath -Force
        Write-Success "Removed $hookPath"
        $removed = $true
    }

    if (Test-Path $hookPathPs1) {
        Remove-Item $hookPathPs1 -Force
        Write-Success "Removed $hookPathPs1"
        $removed = $true
    }

    if ($removed) {
        Write-Success "Pre-push hook removed successfully"
        Write-Info "You can now push without automatic CI checks"
    } else {
        Write-Warning "No pre-push hook found to remove"
    }

    exit 0
}

# Check if hook already exists
if ((Test-Path $hookPath) -or (Test-Path $hookPathPs1)) {
    if (-not $Force) {
        Write-Warning "Pre-push hook already exists"
        Write-Info "Use -Force to overwrite or -Remove to remove it"
        Write-Info "Current hook location: $hookPath"
        exit 1
    } else {
        Write-Warning "Overwriting existing pre-push hook..."
    }
}

# Create hooks directory if it doesn't exist
if (-not (Test-Path $hooksDir)) {
    New-Item -ItemType Directory -Path $hooksDir -Force | Out-Null
    Write-Success "Created hooks directory"
}

# Create the PowerShell hook script
$hookScriptContent = @'
#!/usr/bin/env pwsh
# Git pre-push hook - Runs CI checks before pushing
# Generated by setup_pre_push_hook.ps1

Write-Host ""
Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Blue
Write-Host "  Running CI Checks Before Push" -ForegroundColor Blue
Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Blue
Write-Host ""

# Get the project root (where .git is located)
$projectRoot = Split-Path -Parent $PSScriptRoot
$projectRoot = Split-Path -Parent $projectRoot

# Change to project root
Push-Location $projectRoot

try {
    # Run the CI checks script
    $ciScript = Join-Path $projectRoot "scripts\run_ci_locally.ps1"

    if (-not (Test-Path $ciScript)) {
        Write-Host "⚠ CI check script not found: $ciScript" -ForegroundColor Yellow
        Write-Host "ℹ Skipping CI checks..." -ForegroundColor Cyan
        exit 0
    }

    Write-Host "ℹ Running: $ciScript" -ForegroundColor Cyan
    Write-Host ""

    # Run with Fast mode for quicker checks
    & $ciScript -Fast

    $exitCode = $LASTEXITCODE

    if ($exitCode -ne 0) {
        Write-Host ""
        Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Red
        Write-Host "  ❌ CI Checks Failed - Push Aborted" -ForegroundColor Red
        Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Red
        Write-Host ""
        Write-Host "Fix the issues above and try pushing again." -ForegroundColor Yellow
        Write-Host ""
        Write-Host "To bypass this hook (not recommended):" -ForegroundColor Cyan
        Write-Host "  git push --no-verify" -ForegroundColor Cyan
        Write-Host ""
        Write-Host "To remove this hook:" -ForegroundColor Cyan
        Write-Host "  .\scripts\setup_pre_push_hook.ps1 -Remove" -ForegroundColor Cyan
        Write-Host ""

        exit 1
    }

    Write-Host ""
    Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Green
    Write-Host "  ✅ CI Checks Passed - Proceeding with Push" -ForegroundColor Green
    Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Green
    Write-Host ""

    exit 0

} finally {
    Pop-Location
}
'@

# Write the PowerShell hook script
Set-Content -Path $hookPathPs1 -Value $hookScriptContent -Encoding UTF8
Write-Success "Created PowerShell hook script: $hookPathPs1"

# Create the shell wrapper for Git to execute
$hookWrapperContent = @'
#!/bin/sh
# Git pre-push hook wrapper
# Executes the PowerShell script

# Try to find PowerShell
if command -v pwsh >/dev/null 2>&1; then
    PWSH="pwsh"
elif command -v powershell >/dev/null 2>&1; then
    PWSH="powershell"
else
    echo "⚠ PowerShell not found. Skipping pre-push checks."
    exit 0
fi

# Execute the PowerShell hook script
exec "$PWSH" -NoProfile -ExecutionPolicy Bypass -File "$(dirname "$0")/pre-push.ps1"
'@

# Write the shell wrapper
Set-Content -Path $hookPath -Value $hookWrapperContent -Encoding UTF8 -NoNewline
Write-Success "Created Git hook wrapper: $hookPath"

# Make the hook executable (on Unix-like systems)
if ($IsLinux -or $IsMacOS) {
    chmod +x $hookPath
    Write-Success "Made hook executable"
}

Write-Host ""
Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Green
Write-Host "  ✅ Pre-push Hook Installed Successfully!" -ForegroundColor Green
Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Green
Write-Host ""

Write-Info "The hook will now run automatically before every 'git push'"
Write-Info "It will run CI checks in FAST mode to keep pushes quick"
Write-Host ""

Write-Host "What happens now:" -ForegroundColor Cyan
Write-Host "  1. You run: git push" -ForegroundColor White
Write-Host "  2. Hook runs: .\scripts\run_ci_locally.ps1 -Fast" -ForegroundColor White
Write-Host "  3. If checks pass: Push proceeds ✓" -ForegroundColor Green
Write-Host "  4. If checks fail: Push is aborted ✗" -ForegroundColor Red
Write-Host ""

Write-Host "Bypass options (if needed):" -ForegroundColor Cyan
Write-Host "  • Skip hook once: git push --no-verify" -ForegroundColor White
Write-Host "  • Remove hook: .\scripts\setup_pre_push_hook.ps1 -Remove" -ForegroundColor White
Write-Host ""

Write-Success "Setup complete! Try pushing to test the hook."
