#!/usr/bin/env python3
"""Improved MCP setup script with automatic path resolution.

This script helps configure MemoGraph MCP server for various clients
with proper Python path resolution to avoid "module not found" errors.
"""

import json
import os
import platform
import subprocess
import sys
from pathlib import Path

# Fix encoding for Windows console to support Unicode output
if platform.system() == "Windows":
    try:
        # Try to set UTF-8 encoding for stdout/stderr
        if sys.stdout.encoding != "utf-8":
            sys.stdout.reconfigure(encoding="utf-8")
        if sys.stderr.encoding != "utf-8":
            sys.stderr.reconfigure(encoding="utf-8")
    except (AttributeError, OSError):
        # Fallback: If reconfigure not available or fails, we'll use ASCII-safe output
        pass


def get_python_executable() -> str:
    """Get the full path to the current Python executable."""
    return sys.executable


def get_project_root() -> Path:
    """Get the project root directory."""
    # This script is in scripts/, so parent is project root
    return Path(__file__).parent.parent


def create_wrapper_script(vault_path: str) -> Path:
    """Create a wrapper script that ensures correct Python environment.

    Args:
        vault_path: Path to the MemoGraph vault

    Returns:
        Path to the created wrapper script
    """
    project_root = get_project_root()
    python_exe = get_python_executable()

    system = platform.system()

    if system == "Windows":
        wrapper_path = project_root / "run_memograph_mcp.bat"
        content = f"""@echo off
REM MemoGraph MCP Server Wrapper
REM Auto-generated by setup_mcp.py

cd /d "{project_root}"

REM Use the Python that has memograph installed
"{python_exe}" -m memograph.mcp.run_server
"""
        wrapper_path.write_text(content, encoding="utf-8")
        try:
            print(f"✓ Created wrapper script: {wrapper_path}")
        except UnicodeEncodeError:
            print(f"Created wrapper script: {wrapper_path}")

    else:  # macOS/Linux
        wrapper_path = project_root / "run_memograph_mcp.sh"
        content = f"""#!/bin/bash
# MemoGraph MCP Server Wrapper
# Auto-generated by setup_mcp.py

cd "{project_root}"

# Use the Python that has memograph installed
"{python_exe}" -m memograph.mcp.run_server
"""
        wrapper_path.write_text(content, encoding="utf-8")
        # Make executable
        wrapper_path.chmod(0o755)
        try:
            print(f"✓ Created wrapper script: {wrapper_path}")
        except UnicodeEncodeError:
            print(f"Created wrapper script: {wrapper_path}")

    return wrapper_path


def get_config_path(client: str) -> Path | None:
    """Get configuration file path for a specific MCP client.

    Args:
        client: Client name (claude, cline, bob)

    Returns:
        Path to config file or None if not found
    """
    system = platform.system()

    if client == "claude":
        if system == "Darwin":  # macOS
            return (
                Path.home()
                / "Library/Application Support/Claude/claude_desktop_config.json"
            )
        elif system == "Windows":
            appdata = os.environ.get("APPDATA")
            if appdata:
                return Path(appdata) / "Claude/claude_desktop_config.json"
        elif system == "Linux":
            return Path.home() / ".config/Claude/claude_desktop_config.json"

    elif client == "cline":
        # Try common locations
        paths = [
            Path.home() / ".cline/mcp_settings.json",
            Path.home() / ".config/cline/mcp_settings.json",
        ]
        for path in paths:
            if path.parent.exists():
                return path
        return paths[0]  # Default

    elif client == "bob":
        # Bob-Shell MCP config location
        bob_config = Path.home() / ".bob/mcp_settings.json"
        return bob_config

    return None


def create_mcp_config(
    client: str,
    vault_path: str,
    use_wrapper: bool = True,
    provider: str | None = None,
    model: str | None = None,
) -> dict:
    """Create MCP configuration for a specific client.

    Args:
        client: Client name (claude, cline, bob)
        vault_path: Path to MemoGraph vault
        use_wrapper: If True, use wrapper script; if False, use direct Python path
        provider: Optional LLM provider (ollama, claude, openai)
        model: Optional model name

    Returns:
        Configuration dictionary
    """
    if use_wrapper:
        wrapper_path = create_wrapper_script(vault_path)
        command = str(wrapper_path)
        args = []
    else:
        command = get_python_executable()
        args = ["-m", "memograph.mcp.run_server"]

    env = {"MEMOGRAPH_VAULT": vault_path}
    if provider:
        env["MEMOGRAPH_PROVIDER"] = provider
    if model:
        env["MEMOGRAPH_MODEL"] = model

    if client == "claude":
        return {
            "mcpServers": {
                "memograph": {
                    "command": command,
                    "args": args,
                    "env": env,
                }
            }
        }
    elif client in ("cline", "bob"):
        return {
            "mcp": {
                "servers": {
                    "memograph": {
                        "command": command,
                        "args": args,
                        "env": env,
                    }
                }
            }
        }

    return {}


def merge_config(existing: dict, new: dict) -> dict:
    """Deep merge new config into existing config.

    Args:
        existing: Existing configuration
        new: New configuration to merge

    Returns:
        Merged configuration
    """
    result = existing.copy()

    for key, value in new.items():
        if key in result and isinstance(result[key], dict) and isinstance(value, dict):
            result[key] = merge_config(result[key], value)
        else:
            result[key] = value

    return result


def write_config(client: str, config: dict, backup: bool = True) -> bool:
    """Write configuration to client config file.

    Args:
        client: Client name
        config: Configuration dictionary
        backup: If True, backup existing config

    Returns:
        True if successful, False otherwise
    """
    config_path = get_config_path(client)
    if not config_path:
        try:
            print(f"✗ Could not determine config path for {client}")
        except UnicodeEncodeError:
            print(f"Could not determine config path for {client}")
        return False

    # Create parent directory if needed
    config_path.parent.mkdir(parents=True, exist_ok=True)

    # Backup existing config
    if backup and config_path.exists():
        backup_path = config_path.with_suffix(".json.backup")
        import shutil

        shutil.copy2(config_path, backup_path)
        try:
            print(f"✓ Backed up existing config to: {backup_path}")
        except UnicodeEncodeError:
            print(f"Backed up existing config to: {backup_path}")

    # Load and merge with existing config
    existing = {}
    if config_path.exists():
        try:
            with open(config_path, encoding="utf-8") as f:
                existing = json.load(f)
        except (OSError, json.JSONDecodeError) as e:
            try:
                print(f"⚠ Warning: Could not read existing config: {e}")
            except UnicodeEncodeError:
                print(f"Warning: Could not read existing config: {e}")

    # Merge configurations
    final_config = merge_config(existing, config)

    # Write config
    try:
        with open(config_path, "w", encoding="utf-8") as f:
            json.dump(final_config, f, indent=2)
        try:
            print(f"✓ Wrote config to: {config_path}")
        except UnicodeEncodeError:
            print(f"Wrote config to: {config_path}")
        return True
    except OSError as e:
        try:
            print(f"✗ Failed to write config: {e}")
        except UnicodeEncodeError:
            print(f"Failed to write config: {e}")
        return False


def verify_setup() -> dict:
    """Verify MCP setup.

    Returns:
        Dictionary with verification results
    """
    results = {}

    # Check Python
    results["python"] = {
        "path": sys.executable,
        "version": f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}",
    }

    # Check memograph installation
    try:
        import memograph

        results["memograph"] = {
            "installed": True,
            "version": getattr(memograph, "__version__", "unknown"),
            "path": memograph.__file__,
        }
    except ImportError:
        results["memograph"] = {
            "installed": False,
            "error": "Not installed",
        }

    # Check MCP SDK
    try:
        import mcp

        results["mcp_sdk"] = {
            "installed": True,
            "version": getattr(mcp, "__version__", "unknown"),
        }
    except ImportError:
        results["mcp_sdk"] = {
            "installed": False,
            "error": "Not installed - run: pip install mcp",
        }

    # Test server module
    try:
        result = subprocess.run(
            [sys.executable, "-m", "memograph.mcp.run_server", "--help"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        results["server"] = {
            "working": result.returncode == 0,
            "error": result.stderr if result.returncode != 0 else None,
        }
    except Exception as e:
        results["server"] = {
            "working": False,
            "error": str(e),
        }

    return results


def print_verification(results: dict) -> None:
    """Print verification results in a readable format."""
    print("\n" + "=" * 60)
    print("MemoGraph MCP Setup Verification")
    print("=" * 60)

    # Python
    python = results["python"]
    print(f"\n[OK] Python {python['version']}")
    print(f"     Path: {python['path']}")

    # MemoGraph
    memograph = results["memograph"]
    if memograph["installed"]:
        print(f"\n[OK] MemoGraph v{memograph['version']}")
        print(f"     Path: {memograph['path']}")
    else:
        print(f"\n[FAIL] MemoGraph: {memograph['error']}")

    # MCP SDK
    mcp_sdk = results["mcp_sdk"]
    if mcp_sdk["installed"]:
        print(f"\n[OK] MCP SDK v{mcp_sdk['version']}")
    else:
        print(f"\n[FAIL] MCP SDK: {mcp_sdk['error']}")

    # Server
    server = results["server"]
    if server["working"]:
        print("\n[OK] MCP Server module working")
    else:
        print(f"\n[FAIL] MCP Server: {server.get('error', 'Unknown error')}")

    print("\n" + "=" * 60)


def main():
    """Main entry point."""
    import argparse

    parser = argparse.ArgumentParser(
        description="Setup MemoGraph MCP server with proper path resolution"
    )
    parser.add_argument(
        "--client",
        choices=["claude", "cline", "bob", "all"],
        default="all",
        help="MCP client to configure (default: all)",
    )
    parser.add_argument(
        "--vault",
        default=os.environ.get(
            "MEMOGRAPH_VAULT", str(Path.home() / "Documents/memograph-vault")
        ),
        help="Path to MemoGraph vault (default: $MEMOGRAPH_VAULT or ~/Documents/memograph-vault)",
    )
    parser.add_argument(
        "--provider",
        choices=["ollama", "claude", "openai"],
        help="LLM provider (optional)",
    )
    parser.add_argument(
        "--model",
        help="LLM model name (optional)",
    )
    parser.add_argument(
        "--no-wrapper",
        action="store_true",
        help="Use direct Python path instead of wrapper script",
    )
    parser.add_argument(
        "--verify-only",
        action="store_true",
        help="Only verify setup, don't configure",
    )

    args = parser.parse_args()

    # Use ASCII-safe output if UTF-8 not available
    try:
        print("🔧 MemoGraph MCP Setup")
    except UnicodeEncodeError:
        print("MemoGraph MCP Setup")
    print("=" * 60)

    # Verify setup first
    results = verify_setup()
    print_verification(results)

    if args.verify_only:
        return

    # Check if memograph is installed
    if not results["memograph"]["installed"]:
        try:
            print("\n❌ MemoGraph is not installed!")
        except UnicodeEncodeError:
            print("\nMemoGraph is not installed!")
        print("   Run: pip install -e .")
        sys.exit(1)

    # Create vault if it doesn't exist
    vault_path = Path(args.vault).expanduser()
    if not vault_path.exists():
        try:
            print(f"\n📁 Creating vault at: {vault_path}")
        except UnicodeEncodeError:
            print(f"\nCreating vault at: {vault_path}")
        vault_path.mkdir(parents=True, exist_ok=True)

    # Configure clients
    clients = ["claude", "cline", "bob"] if args.client == "all" else [args.client]

    try:
        print(f"\n⚙️  Configuring {len(clients)} client(s)...")
    except UnicodeEncodeError:
        print(f"\nConfiguring {len(clients)} client(s)...")
    success_count = 0

    for client in clients:
        print(f"\n{client.upper()}:")
        config = create_mcp_config(
            client=client,
            vault_path=str(vault_path),
            use_wrapper=not args.no_wrapper,
            provider=args.provider,
            model=args.model,
        )

        if write_config(client, config):
            success_count += 1

    # Summary
    print("\n" + "=" * 60)
    if success_count == len(clients):
        try:
            print("✅ Setup Complete!")
        except UnicodeEncodeError:
            print("Setup Complete!")
        print(f"\nConfigured {success_count}/{len(clients)} client(s)")
        try:
            print("\n📋 Next Steps:")
        except UnicodeEncodeError:
            print("\nNext Steps:")
        print("  1. Restart your MCP client(s)")
        print("  2. Test with: 'Search my MemoGraph vault'")
        print("  3. Check logs if tools don't appear")
    else:
        try:
            print(f"⚠️  Partial Success: {success_count}/{len(clients)} configured")
        except UnicodeEncodeError:
            print(f"Partial Success: {success_count}/{len(clients)} configured")
        print("\nCheck the errors above and try again.")


if __name__ == "__main__":
    main()
